version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: education-db
    environment:
      POSTGRES_USER: ifortex
      POSTGRES_PASSWORD: ifortex
      POSTGRES_DB: education_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.utf8"
    ports:
      - "5433:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
    driver: local
